const { nextui } = require("@nextui-org/react");
/** @type {import('tailwindcss').Config} */

module.exports = {
  mode: "jit",

  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/Components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{jpg,png,svg}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      mb: "320px",
      mn: "480px",
      mc: "540px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1586px",
      "3xl": "1920px",
    },
    // spacing: {
    //   '1': '0.25rem',
    //   '2': '0.5rem',
    //   '3': '0.75rem',
    //   '4': '1rem',
    //   '5': '1.25rem',
    //   '6': '1.5rem',
    //   '7': '1.75rem',
    //   '8': '2rem',
    //   '9': '2.25rem',
    //   '10': '2.5rem',
    //   '11': '2.75rem',
    //   '12': '3rem',
    //   '13': '3.25rem',
    //   '14': '3.5rem',
    // },
    colors: {
      primaria: "#ffcc00",
      secondary: "",
      "neutral-dark": "#202020",
      "neutral-light": "",
      "suport-dark": "#030303",
      "suport-light": "",
      "cor-preto": "#000000",
      "cor-preto-m": "#3F3F3F",
      cinza: "#969696",
      "cinza-claro": "#ADADAD",
      "cinza-claro-c": "#A1A1A1",
      "cinza-claro-d": "#6D6767",
      "cinza-medio": "#989898",
      "cinza-medio-d": "#D6D6D6",
      "cinza-medio-c": "##D9D9D9",
      "cinza-medio-f": "#909090",
      "cinza-medio-g": "##ECECEC",
      "cinza-skeleton": "rgb(209 213 219)",
      "cinza-escuro": "#696868",
      "amarelo-mostarda": "#584808",
      "amarelo-claro": "#FC0",
      "amarelo-medio": "#E8BA00",
      "amarelo-medio-f": "#FECB07",
      "amarelo-medio-g": "#FDCB01",
      "amarelo-medio-m": "#FBC901",
      branco: "#FFF",
      "branco-claro": "#EAEAEA",
      "branco-medio": "#EEEEEE",
      "branco-medio-m": "#D6D6D6",
      verde: "#009B48",
      "verde-medio": "#33BB89",
      "verde-escuto": "#339500",
      roxo: "#57009B",
    },
    extend: {
      fontFamily: {
        primary: ["var(--font-urbanist)"],
      },
      backgroundImage: {
        login: "url('/images/login.svg')",
        teste: "url('/images/Banner-Categoria.jpg')",
        banner: "url('/images/Banner-categoria.svg')",
        fidelidade: "url('/images/Banner-fidelidade.jpg')",
      },
      height: {
        screendv: "100dvh",
      },
    },
    variants: {
      backgroundColor: [
        "responsive",
        "hover",
        "focus",
        "active",
        "group-hover",
      ],
      transform: ["responsive", "hover", "focus", "active", "group-hover"],
    },
  },

  darkMode: "dark",
  plugins: [nextui()],
};
